#! /bin/sh

### BEGIN INIT INFO
# Provides: logstash
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Should-Start:
# Default-Start: 
# Default-Stop: 0 1 2 3 4 5 6
# Short-Description: Starts up logstash monitoring for condor history records
# Description: Starts up logstash monitoring for condor history records
### END INIT INFO

LOGSTASH_BIN=/opt/logstash/bin/logstash

# Source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog=logstash
pidfile=/var/lock/subsys/logstash-condor-history
config=/var/lib/logstash-condor-history/logstash.conf

start()
{
        if [ ! -e /var/lib/logstash-condor-history ];
        then
            mkdir /var/lib/logstash-condor-history
        fi
        year=`date +"%Y"`
        month=`date +"%m"`
        history_index="osg-connect-job-history-$year-$month"
        cp /etc/logstash/logstash-condor-history.conf /var/lib/logstash-condor-history/logstash.conf
        sed -i "s/HISTORY_INDEX/$history_index/" /var/lib/logstash-condor-history/logstash.conf
        logstash_opts='-f /var/lib/logstash-condor-history/logstash.conf'
        [ $UID -eq 0 ] || exit 4
        [ -x $LOGSTASH_BIN ] || exit 5
        [ -f $config ] || exit 6
	echo -n $"Starting $prog: "
	daemon $LOGSTASH_BIN $logstash_opts
	RETVAL=$?
	echo
	[ $RETVAL = 0 ] && touch $pidfile
	return $RETVAL
}

stop()
{
        [ $UID -eq 0 ] || exit 4
	echo -n $"Shutting down $prog: "
	killproc $LOGSTASH_BIN
	RETVAL=$?
	echo
	rm -f $pidfile
	return $RETVAL
}

reload()
{
	echo -n $"Reloading $prog daemon configuration: "
	killproc $LOGSTASH_BIN -HUP
	RETVAL=$?
	echo
	return $RETVAL
}

report()
{
	echo -n $"Checking SMART devices now: "
	killproc $LOGSTASH_BIN -USR1
	RETVAL=$?
	echo
	return $RETVAL
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload)
		reload
		;;
	report)
		report
		;;
	restart)
		stop
		start
		;;
	condrestart|try-restart)
		if [ -f $pidfile ]; then
			stop
			start
		fi
		;;
	force-reload)
		reload || (stop; start)
		;;
	status)
		status $prog
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status|condrestart|try-restart|reload|force-reload|report}"
		RETVAL=2
		[ "$1" = 'usage' ] && RETVAL=0
esac

exit $RETVAL

