#!/bin/sh
# Init script for collect-history probe
# Implemented based on LSB Core 3.1:
#   * Sections: 20.2, 20.3
#
### BEGIN INIT INFO
# Provides:          collect-history
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: 
# Description:        Starts a python probe that collects HTCondor history
#                     info as a daemon.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

if [ `id -u` -ne 0 ]; then
   echo "You need root privileges to run this script"
   exit 1
fi

name=collect_history
pidfile="/var/run/$name.pid"

RUNTIME_USER=nobody
RUNTIME_GROUP=nobody
RUNTIME_HOME=/tmp
NICE_LEVEL=19

[ -r /etc/default/$name ] && . /etc/default/$name
[ -r /etc/sysconfig/$name.conf ] && . /etc/sysconfig/$name.conf


program=/usr/bin/collect_history_info.py
args="--channel $REDIS_CHANNEL --server $REDIS_SERVER"

start() {


  HOME=${RUNTIME_HOME}
  export PATH HOME

  # set ulimit as (root, presumably) first, before we drop privileges
  # Run the program!
  nice -n ${NICE_LEVEL} chroot --userspec $RUNTIME_USER:$RUNTIME_GROUP / sh -c "
    cd $RUNTIME_HOME
    exec \"$program\" $args
  " > "${LOG_DIR}/$name.stdout" 2> "${LOG_DIR}/$name.err" &

  # Generate the pidfile from here. If we instead made the forked process
  # generate it there will be a race condition between the pidfile writing
  # and a process possibly asking for status.
  echo $! > $pidfile

  echo "$name started."
  return 0
}

stop() {
  # Try a few times to kill TERM the program
  if status ; then
    pid=`cat "$pidfile"`
    echo "Killing $name (pid $pid) with SIGTERM"
    kill -TERM $pid
    # Wait for it to exit.
    for i in 1 2 3 4 5 ; do
      echo "Waiting $name (pid $pid) to die..."
      status || break
      sleep 1
    done
    if status ; then
      echo "$name stop failed; still running."
    else
      echo "$name stopped."
    fi
  fi
}

status() {
  if [ -f "$pidfile" ] ; then
    pid=`cat "$pidfile"`
    if kill -0 $pid > /dev/null 2> /dev/null ; then
      # process by this pid is running.
      # It may not be our pid, but that's what you get with just pidfiles.
      return 0
    else
      return 2 # program is dead but pid file exists
    fi
  else
    return 3 # program is not running
  fi
}

force_stop() {
  if status ; then
    stop
    status && kill -KILL `cat "$pidfile"`
  fi
}


case "$1" in
  start)
    status
    code=$?
    if [ $code -eq 0 ]; then
      echo "$name is already running"
    else
      start
      code=$?
    fi
    exit $code
    ;;
  stop) stop ;;
  force-stop) force_stop ;;
  status) 
    status
    code=$?
    if [ $code -eq 0 ] ; then
      echo "$name is running"
    else
      echo "$name is not running"
    fi
    exit $code
    ;;
  restart) 
    
    stop && start 
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|force-stop|status|restart}" >&2
    exit 3
  ;;
esac

exit $?
